version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "setup.py" }}
            - v1-dependencies-{{ .Branch }}
      - run:
          name: install deps
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -U https://download.pytorch.org/whl/cpu/torch-1.1.0-cp37-cp37m-linux_x86_64.whl
            pip install -U https://download.pytorch.org/whl/cpu/torchvision-0.3.0-cp37-cp37m-linux_x86_64.whl
            pip install -U pytest
            pip install -U .
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest
